version: "3"
services: 
  nginx:
    image: nginx:1.16.0
    ports:
      - "8088:80"
      - "8099:8099"
    links:
      - php-fpm
    volumes:
      - "./nginx/www:/var/www/html"
      - "./nginx/sites:/etc/nginx/sites-enabled"
      - "./nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/logs/:/var/nginx/logs/"
    command: [nginx-debug, '-g', 'daemon off;']

  php-fpm:
    image: bitnami/php-fpm
    volumes:
      - ./nginx/www:/var/www/html
      - ./php-fpm/php.ini:/etc/php/conf/php.ini
    links:
      - mysql
      - redis
 
  mysql:
    image: mysql:5.7
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /var/lib/mysql:/var/lib/mysql    
  
  redis:
    image: redis:4.0
